version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: REACT_APP_WEBSOCKET_URL=ws://localhost:8001 yarn test

      deploy:
        machine:
          enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "24:d1:a8:96:41:be:9c:2d:9b:49:62:a0:07:a8:71:7b"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push https://github.com/AndrewRLloyd88/scheduler.git master:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
